# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\"<\n\x16RaftRequestVoteRequest\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x14\n\x0c\x63\x61ndidate_id\x18\x02 \x01(\t\"\'\n\x17RaftRequestVoteResponse\x12\x0c\n\x04vote\x18\x01 \x01(\x08\":\n\x16RaftUpdateStateRequest\x12\x12\n\nreplica_id\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\"$\n\x0cMergeRequest\x12\x14\n\x0c\x63kpt_diff_id\x18\x01 \x01(\t\"\x0c\n\nGetRequest\"3\n\rModelResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x11\n\thosted_id\x18\x02 \x01(\t\" \n\rEmptyResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\xe6\x01\n\x0eMessageService\x12\x46\n\x0fRaftRequestVote\x12\x17.RaftRequestVoteRequest\x1a\x18.RaftRequestVoteResponse\"\x00\x12<\n\x0fRaftUpdateState\x12\x17.RaftUpdateStateRequest\x1a\x0e.EmptyResponse\"\x00\x12(\n\x05Merge\x12\r.MergeRequest\x1a\x0e.ModelResponse\"\x00\x12$\n\x03Get\x12\x0b.GetRequest\x1a\x0e.ModelResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _RAFTREQUESTVOTEREQUEST._serialized_start=17
  _RAFTREQUESTVOTEREQUEST._serialized_end=77
  _RAFTREQUESTVOTERESPONSE._serialized_start=79
  _RAFTREQUESTVOTERESPONSE._serialized_end=118
  _RAFTUPDATESTATEREQUEST._serialized_start=120
  _RAFTUPDATESTATEREQUEST._serialized_end=178
  _MERGEREQUEST._serialized_start=180
  _MERGEREQUEST._serialized_end=216
  _GETREQUEST._serialized_start=218
  _GETREQUEST._serialized_end=230
  _MODELRESPONSE._serialized_start=232
  _MODELRESPONSE._serialized_end=283
  _EMPTYRESPONSE._serialized_start=285
  _EMPTYRESPONSE._serialized_end=317
  _MESSAGESERVICE._serialized_start=320
  _MESSAGESERVICE._serialized_end=550
# @@protoc_insertion_point(module_scope)
